/**
 * Haraganzito Bedrock candidate exporter.
 *
 * This exporter deliberately labels the output as a candidate route. It does
 * not mutate or destroy the native weighted Armature. The full GLB
 * intermediate remains on Project.haraganzito_source_intermediate.
 */
(function() {
  'use strict';

  const VERSION = '0.1.0';

  function clone(value) {
    return JSON.parse(JSON.stringify(value));
  }

  function jsonText(value) {
    return JSON.stringify(value, null, 2);
  }

  function safeAnimationId(name) {
    return String(name || 'animation')
      .trim()
      .replace(/[^A-Za-z0-9_.-]+/g, '_')
      .replace(/^[^A-Za-z0-9]+/, '')
      .toLowerCase() || 'animation';
  }

  function dataUrlBytes(dataUrl) {
    const match = /^data:([^;]+);base64,(.+)$/s.exec(dataUrl || '');
    if (!match) return null;
    return {
      mime: match[1],
      base64: match[2]
    };
  }

  function makeManifest(name, description, uuid1, uuid2, moduleType, dependency) {
    return {
      format_version: 2,
      header: {
        name,
        description,
        uuid: uuid1,
        version: [1, 0, 0],
        min_engine_version: [1, 21, 0]
      },
      modules: [
        {
          type: moduleType,
          uuid: uuid2,
          version: [1, 0, 0]
        }
      ].concat(dependency ? [{type: 'data', uuid: dependency, version: [1, 0, 0]}] : [])
    };
  }

  function buildBehaviorPack() {
    const bpHeader = guid();
    const bpModule = guid();
    const identifier = 'haraganzito:haraganzito';

    const entity = {
      format_version: '1.21.0',
      'minecraft:entity': {
        description: {
          identifier,
          is_spawnable: true,
          is_summonable: true,
          is_experimental: false
        },
        components: {
          'minecraft:health': {
            value: 20,
            max: 20
          },
          'minecraft:physics': {}
        }
      }
    };

    return {
      manifest: makeManifest(
        'Haraganzito Candidate Behavior',
        'Generated by the Haraganzito bridge. Candidate runtime package.',
        bpHeader,
        bpModule,
        'data'
      ),
      entity
    };
  }

  function buildResourcePack(candidate, source) {
    const rpHeader = guid();
    const rpModule = guid();
    const identifier = 'haraganzito:haraganzito';

    const animationNames = {};
    const animationEntries = {};
    for (const animation of candidate.animations || []) {
      const id = safeAnimationId(animation.name);
      const resourceName = 'animation.haraganzito_' + id;
      animationNames[id] = resourceName;
      animationEntries[resourceName] = {
        animation_length: animation.length,
        loop: animation.loop !== false,
        bones: clone(animation.bones || {})
      };
    }

    const clientEntity = {
      format_version: '1.10.0',
      'minecraft:client_entity': {
        description: {
          identifier,
          materials: {
            default: 'entity'
          },
          textures: {
            default: 'textures/entity/haraganzito'
          },
          geometry: {
            default: 'geometry.haraganzito_candidate'
          },
          animations: animationNames,
          scripts: {
            animate: Object.keys(animationNames).length ? [Object.keys(animationNames)[0]] : []
          },
          render_controllers: [
            'controller.render.haraganzito'
          ]
        }
      }
    };

    const renderController = {
      format_version: '1.8.0',
      render_controllers: {
        'controller.render.haraganzito': {
          geometry: 'Geometry.default',
          materials: [
            {
              '*': 'Material.default'
            }
          ],
          textures: [
            'Texture.default'
          ]
        }
      }
    };

    const report = {
      schema: 'haraganzito.mcaddon.candidate.v1',
      bridgeVersion: VERSION,
      route: candidate.route,
      exact: false,
      runtimeCompatibility: 'requires_target_runtime_validation',
      sourceSummary: source?.source
        ? clone(source.source)
        : null,
      diagnostics: clone(candidate.diagnostics || {}),
      lossModel: clone(candidate.lossModel || {}),
      warnings: [
        'This is a measured rigid-skin candidate, not a lossless weighted-skinned Bedrock representation.',
        'GLB JOINTS_0/WEIGHTS_0 continuous skinning is projected to one bone per triangle.',
        'The native weighted Blockbench project remains the source-preserving representation.',
        'Bedrock runtime acceptance must be tested in the target Minecraft environment.'
      ]
    };

    const manifest = makeManifest(
      'Haraganzito Candidate Resource',
      'Generated by the Haraganzito bridge. Candidate runtime package.',
      rpHeader,
      rpModule,
      'resources',
      bpModule
    );

    return {
      manifest,
      clientEntity,
      renderController,
      animations: {
        format_version: '1.8.0',
        animations: animationEntries
      },
      report
    };
  }

  async function exportCandidate() {
    if (!window.HaraganzitoIterator?.buildRigidPolyMeshCandidate) {
      throw new Error('HARAGANZITO_ITERATOR_NOT_LOADED');
    }
    if (!Project?.haraganzito_source_intermediate) {
      throw new Error('HARAGANZITO_SOURCE_INTERMEDIATE_NOT_AVAILABLE');
    }
    if (typeof JSZip === 'undefined') {
      throw new Error('HARAGANZITO_JSZIP_UNAVAILABLE');
    }

    const source = Project.haraganzito_source_intermediate;
    const candidate = window.HaraganzitoIterator.buildRigidPolyMeshCandidate(source);

    const rp = buildResourcePack(candidate, source);
    const bp = buildBehaviorPack();

    const resourceZip = new JSZip();
    resourceZip.file('manifest.json', jsonText(rp.manifest));
    resourceZip.file(
      'models/entity/haraganzito.geo.json',
      jsonText(candidate.geometry)
    );
    resourceZip.file(
      'animations/haraganzito.animation.json',
      jsonText(rp.animations)
    );
    resourceZip.file(
      'entity/haraganzito.entity.json',
      jsonText(rp.clientEntity)
    );
    resourceZip.file(
      'render_controllers/haraganzito.render_controllers.json',
      jsonText(rp.renderController)
    );
    resourceZip.file(
      'bridge/haraganzito_conversion_report.json',
      jsonText(rp.report)
    );

    const primitive = source.meshes?.[0]?.primitives?.[0];
    const materialIndex = primitive?.material;
    const material = materialIndex == null ? null : source.materials?.[materialIndex];
    const textureIndex = material?.pbrMetallicRoughness?.baseColorTexture?.index;
    const texture = textureIndex == null ? null : source.textures?.[textureIndex];
    const image = texture?.source == null ? null : source.images?.[texture.source];
    const baseColor = dataUrlBytes(image?.dataUrl);

    if (baseColor) {
      const extension = baseColor.mime === 'image/jpeg' ? 'jpg' : 'png';
      resourceZip.file(
        'textures/entity/haraganzito.' + extension,
        baseColor.base64,
        {base64: true}
      );
    }

    const behaviorZip = new JSZip();
    behaviorZip.file('manifest.json', jsonText(bp.manifest));
    behaviorZip.file(
      'entities/haraganzito.entity.json',
      jsonText(bp.entity)
    );

    const [rpBlob, bpBlob] = await Promise.all([
      resourceZip.generateAsync({type: 'blob'}),
      behaviorZip.generateAsync({type: 'blob'})
    ]);

    const addonZip = new JSZip();
    addonZip.file('Haraganzito_Candidate_RP.mcpack', rpBlob);
    addonZip.file('Haraganzito_Candidate_BP.mcpack', bpBlob);
    addonZip.file(
      'BRIDGE_REPORT.json',
      jsonText({
        schema: 'haraganzito.mcaddon.outer_report.v1',
        route: candidate.route,
        exact: false,
        runtimeCompatibility: 'requires_target_runtime_validation',
        sourcePreservedInBlockbench: true
      })
    );

    const addonBlob = await addonZip.generateAsync({type: 'blob'});

    Blockbench.export({
      type: 'Minecraft Add-On Candidate',
      extensions: ['mcaddon'],
      name: 'Haraganzito_Candidate',
      savetype: 'zip',
      content: addonBlob,
      startpath: Project.export_path
    });
  }

  BARS.defineActions(function() {
    new Action('export_haraganzito_rigid_candidate', {
      name: 'Haraganzito: Export Rigid Bedrock Candidate',
      icon: 'archive',
      category: 'file',
      condition: () => !!Project?.haraganzito_source_intermediate,
      click() {
        exportCandidate().catch(error => {
          console.error('[Haraganzito] candidate export failed', error);
          Blockbench.showStatusMessage(
            'Haraganzito export failed: ' + error.message,
            5000
          );
        });
      }
    });
  });

  BBPlugin.register('haraganzito_bedrock_exporter', {
    title: 'Haraganzito Bedrock Candidate Exporter',
    author: 'userblund',
    description: 'Exports the measured rigid Bedrock candidate without mutating the source-preserving native representation.',
    icon: 'archive',
    version: VERSION,
    variant: 'both',
    min_version: '4.10.4',
    onload() {
      console.log('[Haraganzito] Bedrock candidate exporter loaded', VERSION);
    },
    onunload() {}
  });

  globalThis.HaraganzitoBedrockExporter = {
    version: VERSION,
    exportCandidate
  };
})();
